services:
  - type: web
    name: chatia
    env: python
    region: oregon
    plan: free
    rootDirectory: . # Root level to access both folders
    buildCommand: ./build.sh
    startCommand: cd backend && gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///chatia.db
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
